config/routes.rb
Rails.application.routes.draw do
  root to: "brokers#index"
  get 'brokers/import' => 'brokers#my_import'
  resources :brokers do
    collection {post :import}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broker.rb
class Broker < ApplicationRecord
  include Sidekiq::Worker
  sidekiq_options retry: false


  validates :siren, presence: true, allow_nil: false, :length => { :minimum => 9, :maximum => 9 }
  validates_uniqueness_of :siren
  scope :with_localisation, -> { where('latitude is not null') }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brokers_controller.rb
class BrokersController < ApplicationController
  before_action :set_broker, only: [:show, :edit, :update, :destroy]
  include SearchBroker
  include ImportBroker

  def index
    @results = search(params[:search])
    @brokers = Broker.all
    @locations = []
    Broker.with_localisation.find_each {|broker| @locations << {lat: broker.latitude, lng: broker.longitude, siren: broker.siren, name: broker.name}}
  end

  def import
    import_broker_data(params[:file])
    assign_localisation
  end

  def show
    @results = search(params[:search])
  end

  def new
    @broker = Broker.new
  end

  def edit
  end

  def create
    @broker = Broker.new(broker_params)

    respond_to do |format|
      if @broker.save
        format.html { redirect_to @broker, notice: 'Broker was successfully created.' }
        format.json { render :show, status: :created, location: @broker }
      else
        format.html { render :new }
        format.json { render json: @broker.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @place.update(broker_params)
        format.html { redirect_to @broker, notice: 'Broker was successfully updated.' }
        format.json { render :show, status: :ok, location: @broker }
      else
        format.html { render :edit }
        format.json { render json: @broker.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @broker.destroy
    respond_to do |format|
      format.html { redirect_to brokers_url, notice: 'Broker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_broker
    @broker = Broker.find(params[:id])
  end

  def broker_params
    params.require(:broker).permit(:siren, :latitude, :longitude, :division_unite_legale)
  end
end

app/controllers/concerns/import_broker.rb
module ImportBroker

  def import_broker_data(file)
    number_of_brokers_before_import = Broker.all.count
    brokers = []
    CSV.foreach(file.path, headers: true) do |row|
      brokers << row.to_h
    end
    brokers_supposed_to_be_imported = brokers.size
    Broker.import brokers, recursive: true
    brokers_actually_imported = Broker.all.count - number_of_brokers_before_import
    check_integrity_of_import(brokers_supposed_to_be_imported, brokers_actually_imported)
  end

  def check_integrity_of_import(brokers_supposed_to_be_imported, brokers_actually_imported)
    if brokers_supposed_to_be_imported == brokers_actually_imported
      redirect_to root_url, notice: "Successfully imported Brokers! Begin geolocating all Brokers imported... Please refresh the page in a couple minutes for the mapping"
    else
      redirect_to root_url, notice: "#{brokers_supposed_to_be_imported - brokers_actually_imported} brokers havn't been imported on #{brokers_actually_imported}... Please refresh the page in a couple minutes for the mapping"
    end
  end

  def assign_localisation
    AssignLocalisationBrokerWorker.perform_async
  end
end

app/controllers/concerns/search_broker.rb
module SearchBroker
  def search(search)
    result = []
    if search
      broker = Broker.find_by(siren: search)
      if broker
        redirect_to broker_path(broker.id)
      else
        redirect_to root_url, notice: "We don't have this Siren in database"
      end
    else
      result
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brokers_helper.rb
module BrokersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/brokers/_map_all_brokers.html.erb
<script type="text/javascript">
  function initMap() {
  const map = new google.maps.Map(document.getElementById("map"), {
    zoom: 3,
    center: { lat: 48.8534, lng: 2.3488 },
  });
  // Create an array of alphabetical characters used to label the markers.
  const labels = "B";
  // Add some markers to the map.
  // Note: The code uses the JavaScript Array.prototype.map() method to
  // create an array of markers based on a given "locations" array.
  // The map() method here has nothing to do with the Google Maps API.
  const infowindow = new google.maps.InfoWindow({
    content: "yoli",
  });

  const markers = locations.map((location, i) => {
    return new google.maps.Marker({
      position: location,
      label: labels[i % labels.length],
    });
  });

  markers.forEach((marker,index) => {
      marker.addListener("click", () => {
        infowindow.setContent(`${locations[index]["siren"]}`);
        infowindow.open(map, marker);
      });
});

  // Add a marker clusterer to manage the markers.

  new MarkerClusterer(map, markers, {
    imagePath:
      "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m",
  });
}
  const locations =
  [
  <%@locations.each do |loca|%>
    {lat:<%=loca.values[0]%>, lng:<%=loca.values[1]%>, siren:<%=loca.values[2]%>},
  <%end%>
    ];

</script>

app/views/brokers/_map_broker.html.erb
<script type="text/javascript">
  function initMap() {
  const map = new google.maps.Map(document.getElementById("map"), {
    zoom: 3,
    center: { lat: 48.8534, lng: 2.3488 },
  });
  // Create an array of alphabetical characters used to label the markers.
  const labels = "B";
  // Add some markers to the map.
  // Note: The code uses the JavaScript Array.prototype.map() method to
  // create an array of markers based on a given "locations" array.
  // The map() method here has nothing to do with the Google Maps API.
  const markers = locations.map((location, i) => {
    return new google.maps.Marker({
      position: location,
      label: labels[i % labels.length],
    });
  });

  // Add a marker clusterer to manage the markers.

  new MarkerClusterer(map, markers, {
    imagePath:
      "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m",
  });
}
  const locations =
  [
    {lat:<%=@broker.latitude%>, lng:<%=@broker.longitude%>},
    ];

</script>

app/views/brokers/index.html.erb
  <div class="jumbotron">
    <h1 class="display-4 text-info">Welcome in the BrokerApp ! </h1>
    <p class="lead">You can import a list of Siren, the BrokerApp will geolocate and map them just below for you !</p>
    <p class="lead">Use the search bar to get more information about a particular broker.</p>
  </div>
  <%=form_tag import_brokers_path, multipart: true do%>
    <ol class="breadcrumb m-4 border border-info">
      <li class=""><%= file_field_tag :file, class:""%></li>
      <li class=""><%= submit_tag "Import from file", class:""%></li>
    </ol>
  <% end %>
<%= render "brokers/map_all_brokers" %>

app/views/brokers/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#"><%= link_to "Home", root_url%></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= link_to @broker.siren, broker_path%></li>
  </ol>
</nav>
<div class="d-flex justify-content-center">
  <div class="card" style="width: 400px;">
    <div class="card-body">
      <% if @broker.name == nil %>
        <h5 class="card-title">This siren is in the database but we couldn't retrieve informations for this broker</h5>
      <% else %>
        <h5 class="card-title"><%= @broker.name.upcase %></h5>
        <p class="card-text"><%= @broker.address %> </p>
        <p class="card-text"><%= @broker.division_unite_legale %></p>
      <% end %>
      <p>SIREN : <%= @broker.siren %></p>
      <%= link_to(brokers_path) do %>
      <button type="button" class="btn btn-primary">Back</button>
      <%end%>
    </div>
  </div>
</div>
<div class="m-5">
  <%= render "brokers/map_broker" %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <li class="navbar-brand" style="text-decoration:underline"><%= link_to "BrokerApp", brokers_path, style:"padding-bottom:35px;color:inherit;color:white;"%></li>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", brokers_path, style:"padding-bottom:35px;color:inherit;color:white;"%>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= form_tag brokers_path, method: :get do %>
      <%= text_field_tag :search, params[:search], class:"form-control mr-sm-2", placeholder:"Siren" %>
      <%= submit_tag ("Siren search"), class:"btn btn-outline-success my-2 my-sm-0"%>
      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoggoCsvApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.3/cjs/popper-base.min.js" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js"></script>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCd70oxC1NLmfGEbC48zwiUSIDiSFQFImw&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
    <div id="map"></div>
  </body>
</html>